config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'public/publics#index'

  # admin_menuルーティング
  scope '/admin_menu' do
    get '/', to: 'dashbords#index', as: :dashbords

    get '/users/', to: 'users#index'
    get '/users/signup', to: 'users#signup'
    post '/users/signup', to: 'users#create'
    get '/users/:id', to: 'users#show', as: :user
    get '/users/:id/edit', to: 'users#edit', as: :edit_user
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: :users_destroy

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', as: :logout

    resources :plans, :providers, :net_lines,
              :services, :devices, :data_capacities,
              :campaigns
  end

  resources :plans, module: 'public', only: [ :index, :show ] do
    collection do
      get :search
    end
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plans_devices
  has_many :devices, through: :plans_devices
  has_many :plans_services
  has_many :services, through: :plans_services
  has_many :plans_campaigns
  has_many :campaigns, through: :plans_campaigns
  belongs_to :data_capacity
  belongs_to :provider
  belongs_to :net_line
  belongs_to :service

  accepts_nested_attributes_for :devices
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController 

  layout 'admin_menu'

  def index
    @plans = Plan.all.includes(:provider, :service, :devices)
    render '/admin_menu/plans/index'
  end

  def new
    @plan = Plan.new
    render new_plan_path
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to @plan
    else
      render new_plan_path
    end
  end

  def show
    @plan = Plan.find(params[:id])
    render '/admin_menu/plans/show'
  end

  def edit
    @plan = Plan.find(params[:id])
    render '/admin_menu/plans/edit'
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update_attributes(plan_params)
      redirect_to @plan
    else
      render '/admin_menu/plans/edit'
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    if @plan.destroy
    # 成功時のメッセージを格納する
      flash[:success] = "ユーザーを削除しました"
    # ユーザー一覧画面を表示する
      redirect_to controller: :plans, action: :index
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:name, :p_content, :construct_period,
                                 :total_fee, :plan_device_fee, :plan_url,
                                 :net_line_id, :plan_device_id, :data_capacity_id,
                                 :provider_id, { :campaign_ids=> [] },
                                 { :service_ids=> [] }, { :device_ids=> [] }
                                )
  end

end

app/views/admin_menu/plans/edit.html.erb
<div class="Admin">
  <div class="Admin__content">
    <%= form_with model: @plan, local: true do |f| %>
    <div class="AdminCard">
      <div class="AdminCard__content--edit">
        <%= f.label :name, 'プラン' %>
        <%= f.text_field :name %>

        <%= f.label :p_content, 'プラン内容' %>
        <%= f.text_field :p_content %>

        <%= f.label :construct_period, '契約期間' %>
        <%= f.text_field :construct_period %>

        <%= f.label :total_fee, '合計金額' %>
        <%= f.text_field :total_fee %>

        <%= f.label :plan_device_fee, '端末代金' %>
        <%= f.text_field :plan_device_fee %>

        <%= f.label :plan_url, 'リンクURL' %>
        <%= f.text_field :plan_url %>

        <%= f.label :campaign_ids %>
        <%= collection_check_boxes :plan, :campaign_ids, Campaign.all, :id, :name %>

        <%= f.label :net_line_id %>
        <%= f.collection_select :net_line_id, NetLine.all, :id, :name %>

        <%= f.label :service_ids %>
        <%= collection_check_boxes :plan, :service_ids, Service.all, :id, :name %>

        <%= f.label :data_capacity_id %>
        <%= f.collection_select :data_capacity_id, DataCapacity.all, :id, :name %>

        <%= f.label :provider_id %>
        <%= f.collection_select :provider_id, Provider.all, :id, :name %>

        <%= f.label :device_ids %>
        <%= collection_check_boxes :plan, :device_ids, Device.all, :id, :name %>

        <%= f.submit %>
      </div>
    </div>
    <% end %>

    <%= link_to '新規作成', new_plan_path %>
    <%= link_to '削除', plan_path(@plan), method: :delete, data: { confirm: '本当に削除しますか？' } %>
  </div>
</div>

app/views/admin_menu/plans/index.html.erb
<div class="Admin">
  <h1>プラン一覧</h1>
  <%= link_to '新規作成', new_plan_path, { class: "Admin__link"} %>
  <div class="Admin__content">
    <% @plans.each do |plan| %>
    <div class="AdminCard">
      <div class="AdminCard__top">
        <h2><%= plan.name %><%= plan.provider.name %></h2>
      </div>
      <div class="AdminCard__content">

        <p>ID:<%= plan.id %></p>

        <p>プラン:<%= link_to plan.name, edit_plan_path(plan) %></p>

        <p>プラン内容:<%= plan.p_content %></p>

        <p>契約期間:<%= plan.construct_period %></p>

        <p>総合計金額:<%= plan.total_fee %></p>

        <p>端末代金:<%= plan.plan_device_fee %></p>

        <p>URL:<%= plan.plan_url %></p>

        <p>キャンペーン</p>
        <p>
          <% plan.plans_campaigns.each do |plan_campaigns| %>
          <%= plan_campaigns.campaign.name %>
          <% end %>
        </p>

        <p>データ通信量:<%= plan.data_capacity.name %></p>

        <p>プロバイダー:<%= plan.provider.name %></p>

        <p>カテゴリ</p>
        <p>
          <% plan.plans_services.each do |plan_services| %>
          <%= plan_services.service.name %>
          <% end %>
        </p>


        <p>端末</p>
        <p>
          <% plan.plans_devices.each do |plan_devices| %>
          <%= plan_devices.device.name %>
          <% end %>
        </p>

        <p><%= link_to '削除', plan_path(plan), method: :delete, data: { confirm: '本当に削除しますか？' } %></p>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin_menu/plans/new.html.erb
<%= form_with model: @plan, method: :post do |f| %>

  <%= f.label :name, 'プラン' %>
  <%= f.text_field :name %>

  <%= f.label :p_content, 'プラン内容' %>
  <%= f.text_field :p_content %>

  <%= f.label :construct_period, '契約期間' %>
  <%= f.text_field :construct_period %>

  <%= f.label :total_fee, '合計金額' %>
  <%= f.text_field :total_fee %>

  <%= f.label :plan_device_fee, '端末代金' %>
  <%= f.text_field :plan_device_fee %>

  <%= f.label :plan_url, 'リンクURL' %>
  <%= f.text_field :plan_url %>

  <%= f.label :campaign_ids %>
  <%= f.collection_check_boxes :campaign_ids, Campaign.all, :id, :name %>

  <%= f.label :net_line_id %>
  <%= f.collection_select :net_line_id, NetLine.all, :id, :name %>

  <%= f.label :service_ids %>
  <%= f.collection_check_boxes :service_ids, Service.all, :id, :name %>

  <%= f.label :data_capacity_id %>
  <%= f.collection_select :data_capacity_id, DataCapacity.all, :id, :name %>

  <%= f.label :provider_id %>
  <%= f.collection_select :provider_id, Provider.all, :id, :name %>

  <%= f.label :device_ids %>
  <%= f.collection_check_boxes :device_ids, Device.all, :id, :name %>

  <%= f.submit %>
<% end %>

app/views/admin_menu/plans/show.html.erb
<div>
  <%= link_to 'プラン一覧', plans_path %>
  <p>ID：<%= @plan.id %></p>
  <p>プラン：<%= @plan.name %></p>
  <p>プラン内容：<%= @plan.p_content %></p>
  <p>契約期間：<%= @plan.construct_period %></p>
  <p>総合計金額：<%= @plan.total_fee %></p>
  <p>端末代金：<%= @plan.plan_device_fee %></p>
  <p>URL：<%= @plan.plan_url %></p>
  <% @plan.plans_campaigns.each do |plan_campaigns| %>
    <p>キャンペーン：<%= plan_campaigns.campaign.name %></p>
  <% end %>
  <p>データ通信量：<%= @plan.data_capacity.name %></p>
  <p>プロバイダー：<%= @plan.provider.name %></p>
  <% @plan.plans_services.each do |plan_services| %>
    <p>サービス：<%= plan_services.service.name %></p>
  <% end %>
  <% @plan.plans_devices.each do |plan_devices| %>
    <p>端末：<%= plan_devices.device.name %></p>
  <% end %>
  <%= link_to '編集', edit_plan_path(@plan) %>
  <%= link_to '削除', plan_path(@plan), method: :delete, data: { confirm: "本当に削除しますか？"} %>
</div>