config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'public/publics#index'

  # admin_menuルーティング
  scope '/admin_menu' do
    get '/', to: 'dashbords#index', as: :dashbords

    get '/users/', to: 'users#index'
    get '/users/signup', to: 'users#signup'
    post '/users/signup', to: 'users#create'
    get '/users/:id', to: 'users#show', as: :user
    get '/users/:id/edit', to: 'users#edit', as: :edit_user
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: :users_destroy

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', as: :logout

    resources :plans, :providers, :net_lines,
              :services, :devices, :data_capacities,
              :campaigns
  end

  resources :plans, module: 'public', only: [ :index, :show ] do
    collection do
      get :search
    end
  end

end

app/models/net_line.rb
class NetLine < ApplicationRecord
  has_many :plans
end

app/controllers/net_lines_controller.rb
class NetLinesController < ApplicationController 

  layout 'admin_menu'

  def index
    @net_lines = NetLine.all
    render '/admin_menu/net_lines/index'
  end

  def new
    @net_line = NetLine.new
    render new_net_line_path
  end

  def create
    @net_line = NetLine.new(net_line_params)
    if @net_line.save
      redirect_to @net_line
    else
      render new_net_line_path
    end
  end

  def show
    @net_line = NetLine.find(params[:id])
    render '/admin_menu/net_lines/show'
  end

  def edit
    @net_line = NetLine.find(params[:id])
    render '/admin_menu/net_lines/edit'
  end

  def update
    @net_line = NetLine.find(params[:id])
    if @net_line.update_attributes(net_line_params)
      redirect_to @net_line
    else
      render '/admin_menu/net_lines/edit'
    end
  end

  def destroy
    @net_line = NetLine.find(params[:id])
    if @net_line.destroy
    # 成功時のメッセージを格納する
      flash[:success] = "ユーザーを削除しました"
    # ユーザー一覧画面を表示する
      redirect_to controller: :netlines, action: :index
    end
  end

  private

  def net_line_params
    params.require(:net_line).permit(:name, :service_id)
  end

end

app/views/admin_menu/net_lines/edit.html.erb
<div class="Admin">
  <div class="Admin__content">
    <%= form_with model: @net_line do |f| %>
    <div class="AdminCard">
      <div class="AdminCard__content--edit">

        <%= f.label :name, '回線' %>
        <%= f.text_field :name %>

        <%= f.submit %>
      </div>
    </div>
    <% end %>

    <%= link_to '新規作成', new_net_line_path %>
    <%= link_to '削除', net_line_path(@net_line), method: :delete, data: { confirm: '関連プランも削除されます。本当に削除しますか？' }%>
  </div>
</div>

app/views/admin_menu/net_lines/index.html.erb
<div class="Admin">
  <h1>回線一覧</h1>
  <%= link_to '新規作成', new_net_line_path %>
  <div class="Admin__content">
    <% @net_lines.each do |net_line| %>
    <div class="AdminCard">
      <div class="AdminCard__top">
        <h2><%= link_to net_line.name, edit_net_line_path(net_line) %></h2>
      </div>
      <div class="AdminCard__content">
        <p>ID：<%= net_line.id %></p>
        <p><%= link_to '削除', net_line_path(net_line), method: :delete, data: { confirm: '関連プランも削除されます。本当に削除しますか？' } %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin_menu/net_lines/new.html.erb
<%= form_with model: @net_line, method: :post do |f| %>

  <%= f.label :name, '回線名' %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/admin_menu/net_lines/show.html.erb
<div>
  <%= link_to '回線一覧', net_lines_path %>
  <p>ID：<%= @net_line.id %></p>
  <p>回線：<%= @net_line.name %></p>
  <p>サービス：<%= @net_line.name %></p>
  <%= link_to '編集', net_line_path(@net_line) %>
  <%= link_to '削除', net_line_path(@net_line), method: :delete, data: { confirm: "本当に削除しますか？"} %>
</div>