config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'public/publics#index'

  # admin_menuルーティング
  scope '/admin_menu' do
    get '/', to: 'dashbords#index', as: :dashbords

    get '/users/', to: 'users#index'
    get '/users/signup', to: 'users#signup'
    post '/users/signup', to: 'users#create'
    get '/users/:id', to: 'users#show', as: :user
    get '/users/:id/edit', to: 'users#edit', as: :edit_user
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: :users_destroy

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', as: :logout

    resources :plans, :providers, :net_lines,
              :services, :devices, :data_capacities,
              :campaigns
  end

  resources :plans, module: 'public', only: [ :index, :show ] do
    collection do
      get :search
    end
  end

end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :plans
  has_many :data_capacities
  has_many :campaigns
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController 

  layout 'admin_menu'

  def index
    @providers = Provider.all
    render '/admin_menu/providers/index'
  end

  def new
    @provider = Provider.new
    render new_provider_path
  end

  def create
    @provider = Provider.new(provider_params)
    if @provider.save
      redirect_to @provider
    else
      flash[:alert] = '失敗'
      render new_provider_path
    end
  end

  def show
    @provider = Provider.find(params[:id])
    render '/admin_menu/providers/show'
  end

  def edit
    @provider = Provider.find(params[:id])
    render '/admin_menu/providers/edit'
  end

  def update
    @provider = Provider.find(params[:id])
    if @provider.update_attributes(provider_params)
      redirect_to @provider
    else
      render '/admin_menu/data_capacities/edit'
    end
  end

  def destroy
    @provider = Provider.find(params[:id])
    if @provider.destroy
    # 成功時のメッセージを格納する
      flash[:success] = "ユーザーを削除しました"
    # ユーザー一覧画面を表示する
      redirect_to controller: :providers, action: :index
    end
  end

  def provider_params
    params.require(:provider).permit(:name, :service_id)
  end
end

app/views/admin_menu/providers/edit.html.erb
<div class="Admin">
  <div class="Admin__content">
    <%= form_with model: @provider, local: true do |f| %>
    <div class="AdminCard">
      <div class="AdminCard__content--edit">

        <%= f.label :name, 'プロバイダー' %>
        <%= f.text_field :name %>

        <%= f.submit %>
      </div>
    </div>
    <% end %>

    <%= link_to '新規作成', new_provider_path %>
    <%= link_to '削除', provider_path(@provider), method: :delete, data: { confirm: '関連プランも削除されます。本当に削除しますか？' } %>
  </div>
</div>

app/views/admin_menu/providers/index.html.erb
<div class="Admin">
  <h1>プロバイダー一覧</h1>
  <%= link_to '新規作成', new_provider_path, { class: "Admin__link" } %>
  <div class="Admin__content">
    <% @providers.each do |provider| %>
    <div class="AdminCard">
      <div class="AdminCard__top">
        <h2><%= link_to provider.name, edit_provider_path(provider) %></h2>
      </div>
      <div class="AdminCard__content">
    <p>ID：<%= provider.id %></p>
          <p><%= link_to '削除', provider_path(provider), method: :delete, data: { confirm: '関連プランも削除されます。本当に削除しますか？' } %>
          </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin_menu/providers/new.html.erb
<% flash[:alert] if flash[:alert] %>
<%= form_with model: @provider, method: :post, local: true do |f| %>

  <%= f.label :name, 'プロバイダ名' %>
  <%= f.text_field :name %>
  
  <%= f.submit %>
<% end %>

app/views/admin_menu/providers/show.html.erb
<div>
  <%= link_to 'プロバイダー一覧', providers_path %>
  <%= @provider.name %>
  <%= link_to '編集', edit_provider_path(@provider) %>
  <%= link_to '削除', provider_path(@provider), method: :delete, data: { confirm: "本当に削除しますか？"} %>
</div>