config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'public/publics#index'

  # admin_menuルーティング
  scope '/admin_menu' do
    get '/', to: 'dashbords#index', as: :dashbords

    get '/users/', to: 'users#index'
    get '/users/signup', to: 'users#signup'
    post '/users/signup', to: 'users#create'
    get '/users/:id', to: 'users#show', as: :user
    get '/users/:id/edit', to: 'users#edit', as: :edit_user
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: :users_destroy

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', as: :logout

    resources :plans, :providers, :net_lines,
              :services, :devices, :data_capacities,
              :campaigns
  end

  resources :plans, module: 'public', only: [ :index, :show ] do
    collection do
      get :search
    end
  end

end

app/views/layouts/admin_menu.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= display_meta_tags(default_meta_tags) %>
    <% set_meta_tags noinex: true, nofollow: true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash[:alert] if flash[:alert] %>
    <a href="/">トップ</a>
    <% if request.path != '/admin_menu' %>
    <%= link_to '管理画面トップ', dashbords_path %>
    <% end %>
    <% if logged_in? %>
    <%= link_to 'ログアウト', logout_path, method: :delete %>
    <% else %>
    <%= link_to 'ログイン', login_path %>
    <% end %>
    <div class="BaseLayout">
      <div class="Header">
        <h2 class="Header__title">maprice admin</h2>
      </div>
      <ul class="GlobalNavi">
        <li class="GlobalNavi__menu"><%= link_to '管理画面トップ', controller: 'dashbords', action: 'index' %></li>
        <li class="GlobalNavi__menu"><%= link_to 'プラン一覧', plans_path %></li>
        <li class="GlobalNavi__menu"><%= link_to 'キャンペーン一覧', campaigns_path %></li>
        <li class="GlobalNavi__menu"><%= link_to '通信容量一覧' , data_capacities_path %></li>
        <li class="GlobalNavi__menu"><%= link_to '端末一覧', devices_path %></li>
        <li class="GlobalNavi__menu"><%= link_to '回線一覧' , net_lines_path %></li>
        <li class="GlobalNavi__menu"><%= link_to 'サービス一覧', services_path %></li>
        <li class="GlobalNavi__menu"><%= link_to 'プロバイダー一覧', providers_path %></li>
        <li class="GlobalNavi__menu"><%= link_to 'ユーザー一覧', users_path %></li>
      </ul>
      <div class="Content">
        <%= yield %>
      </div>
      <div class="Footer">
        <div class="Footer__content">
          <div class="Footer__item"><a href="/">TOP</a></div>
          <div class="Footer__item"><a href="/plans">WiFi</a></div>
          <div class="Footer__item"><a href="#">利用規約</a></div>
          <div class="Footer__item"><a href="#">プライバシーポリシー</a></div>
          <div class="Footer__item"><a href="#">特定商取引に基づく表記</a></div>
        </div>
        <div class="Footer__copyright">
          <small>&copy;2019 maprice</small>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>
    <div class="BaseLayout">
      <div class="Header">
        <h2 class="Header__title">maprice</h2>
      </div>
      <ul class="GlobalNavi">
        <li class="GlobalNavi__menu"><a href="/">TOP</a></li>
        <li class="GlobalNavi__menu"><a href="/plans">WiFiを探す</a></li>
      </ul>
      <div class="Content">
        <%= yield %>
      </div>
      <div class="Footer">
        <div class="Footer__content">
          <div class="Footer__item"><a href="/">TOP</a></div>
          <div class="Footer__item"><a href="/plans">WiFi</a></div>
          <div class="Footer__item"><a href="#">利用規約</a></div>
          <div class="Footer__item"><a href="#">プライバシーポリシー</a></div>
          <div class="Footer__item"><a href="#">特定商取引に基づく表記</a></div>
        </div>
        <div class="Footer__copyright">
          <small>&copy;2019 maprice</small>
        </div>
      </div>
    </div>
  </body>
</html>